mouth: list = ["Janeiro",
               "Fevereiro",
               "Março",
               "Abril",
               "Maio",
               "Junho",
               "Julho",
               "Agosto",
               "Setembro",
               "Outubro",
               "Novembro",
               "Dezembro"]

internet: list = [0.00,
                  0.00,
                  118.39,
                  114.89,
                  114.89,
                  114.77,
                  114.89,
                  96.18,
                  114.89,
                  114.89,
                  77.99,
                  107.24]